// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/magomedcoder/gskeleton/internal/config"
	"github.com/magomedcoder/gskeleton/internal/provider"
	"github.com/magomedcoder/gskeleton/internal/transport/json-rpc/handler"
	"github.com/magomedcoder/gskeleton/pkg/json-rpc-server"
)

// Injectors from wire.go:

func Initialize(conf *config.Config) *Provider {
	example := handler.NewExampleHandler()
	handlerHandler := &handler.Handler{
		Example: example,
	}
	server := provider.NewJsonRpcServer(conf, handlerHandler)
	mainProvider := &Provider{
		Server: server,
	}
	return mainProvider
}

// wire.go:

type Provider struct {
	Server *json_rpc_server.Server
}

var newSet = wire.NewSet(wire.Struct(new(Provider), "*"), wire.Struct(new(handler.Handler), "*"), provider.NewJsonRpcServer, handler.NewExampleHandler)
