// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/magomedcoder/gskeleton/internal/config"
	"github.com/magomedcoder/gskeleton/internal/provider"
	"github.com/magomedcoder/gskeleton/internal/repository/user/repo"
	"github.com/magomedcoder/gskeleton/internal/service/user"
	"github.com/magomedcoder/gskeleton/internal/transport/http"
	"github.com/magomedcoder/gskeleton/internal/transport/http/handler"
	"github.com/magomedcoder/gskeleton/internal/transport/http/handler/v1"
	"github.com/magomedcoder/gskeleton/internal/transport/http/middleware"
	"github.com/magomedcoder/gskeleton/internal/transport/http/router"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *http.AppProvider {
	db := provider.NewPostgresDB(conf)
	userRepository := repo.NewUserRepository(db)
	userService := user.NewUserService(userRepository)
	example := v1.NewPostHandler(userService)
	v1V1 := &v1.V1{
		Example: example,
	}
	handlerHandler := &handler.Handler{
		V1: v1V1,
	}
	authMiddleware := middleware.NewAuthMiddleware()
	middlewareHandler := &middleware.Handler{
		AuthMiddleware: authMiddleware,
	}
	engine := router.NewRouter(handlerHandler, middlewareHandler)
	appProvider := &http.AppProvider{
		Engine: engine,
		Config: conf,
	}
	return appProvider
}
