// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"golang-app-skeleton/internal/config"
	"golang-app-skeleton/internal/provider"
	"golang-app-skeleton/internal/transport/app/handler"
	"golang-app-skeleton/pkg/server"
)

// Injectors from wire.go:

func Initialize(conf *config.Config) *Provider {
	example := handler.NewExampleHandler()
	handlerHandler := &handler.Handler{
		Example: example,
	}
	server := provider.NewRpcServer(conf, handlerHandler)
	mainProvider := &Provider{
		Server: server,
	}
	return mainProvider
}

// wire.go:

type Provider struct {
	Server *server.Server
}

var newSet = wire.NewSet(wire.Struct(new(Provider), "*"), wire.Struct(new(handler.Handler), "*"), provider.NewRpcServer, handler.NewExampleHandler)
