// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type Create_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create_Request) Reset() {
	*x = Create_Request{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Request) ProtoMessage() {}

func (x *Create_Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Request.ProtoReflect.Descriptor instead.
func (*Create_Request) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Create_Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Create_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Create_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create_Response) Reset() {
	*x = Create_Response{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Response) ProtoMessage() {}

func (x *Create_Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Response.ProtoReflect.Descriptor instead.
func (*Create_Response) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Create_Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Create_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Get_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Request) Reset() {
	*x = Get_Request{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Request) ProtoMessage() {}

func (x *Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Request.ProtoReflect.Descriptor instead.
func (*Get_Request) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Get_Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Get_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreateAt      string                 `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Response) Reset() {
	*x = Get_Response{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Response) ProtoMessage() {}

func (x *Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Response.ProtoReflect.Descriptor instead.
func (*Get_Response) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Get_Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Get_Response) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Get_Response) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x13gskeleton.grpc.user\"\x81\x01\n" +
	"\x06Create\x1aA\n" +
	"\aRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x1a4\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x80\x01\n" +
	"\x03Get\x1a%\n" +
	"\aRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x1aR\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bcreateAt\x18\x03 \x01(\tR\bcreateAt2\xb2\x01\n" +
	"\vUserService\x12U\n" +
	"\x06Create\x12#.gskeleton.grpc.user.Create.Request\x1a$.gskeleton.grpc.user.Create.Response\"\x00\x12L\n" +
	"\x03Get\x12 .gskeleton.grpc.user.Get.Request\x1a!.gskeleton.grpc.user.Get.Response\"\x00B/Z-github.com/magomedcoder/gskeleton/api/grpc/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*Create)(nil),          // 0: gskeleton.grpc.user.Create
	(*Get)(nil),             // 1: gskeleton.grpc.user.Get
	(*Create_Request)(nil),  // 2: gskeleton.grpc.user.Create.Request
	(*Create_Response)(nil), // 3: gskeleton.grpc.user.Create.Response
	(*Get_Request)(nil),     // 4: gskeleton.grpc.user.Get.Request
	(*Get_Response)(nil),    // 5: gskeleton.grpc.user.Get.Response
}
var file_user_proto_depIdxs = []int32{
	2, // 0: gskeleton.grpc.user.UserService.Create:input_type -> gskeleton.grpc.user.Create.Request
	4, // 1: gskeleton.grpc.user.UserService.Get:input_type -> gskeleton.grpc.user.Get.Request
	3, // 2: gskeleton.grpc.user.UserService.Create:output_type -> gskeleton.grpc.user.Create.Response
	5, // 3: gskeleton.grpc.user.UserService.Get:output_type -> gskeleton.grpc.user.Get.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
