// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/magomedcoder/gskeleton/internal/config"
)

// Injectors from wire.go:

func Initialize(config2 *config.Config) (Provider, error) {
	provider := Provider{}
	return provider, nil
}

// wire.go:

type Provider struct {
}
