// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/magomedcoder/gskeleton/api/grpc/pb/auth"
	user2 "github.com/magomedcoder/gskeleton/api/grpc/pb/user"
	"github.com/magomedcoder/gskeleton/internal/config"
	"github.com/magomedcoder/gskeleton/internal/provider"
	"github.com/magomedcoder/gskeleton/internal/repository/user/repo"
	"github.com/magomedcoder/gskeleton/internal/service/user"
	"github.com/magomedcoder/gskeleton/internal/transport/grpc"
	handler2 "github.com/magomedcoder/gskeleton/internal/transport/grpc/handler"
	middleware2 "github.com/magomedcoder/gskeleton/internal/transport/grpc/middleware"
	"github.com/magomedcoder/gskeleton/internal/transport/http"
	"github.com/magomedcoder/gskeleton/internal/transport/http/handler"
	"github.com/magomedcoder/gskeleton/internal/transport/http/handler/v1"
	"github.com/magomedcoder/gskeleton/internal/transport/http/middleware"
	"github.com/magomedcoder/gskeleton/internal/transport/http/router"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *http.AppProvider {
	db := provider.NewPostgresDB(conf)
	userRepository := repo.NewUserRepository(db)
	userService := user.NewUserService(userRepository)
	v1User := v1.NewPostHandler(userService)
	v1V1 := &v1.V1{
		User: v1User,
	}
	handlerHandler := &handler.Handler{
		V1: v1V1,
	}
	authMiddleware := middleware.NewAuthMiddleware()
	middlewareMiddleware := &middleware.Middleware{
		AuthMiddleware: authMiddleware,
	}
	engine := router.NewRouter(handlerHandler, middlewareMiddleware)
	appProvider := &http.AppProvider{
		Conf:   conf,
		Engine: engine,
	}
	return appProvider
}

func NewGrpcInjector(conf *config.Config) *grpc.AppProvider {
	tokenMiddleware := middleware2.NewTokenMiddleware(conf)
	grpcMethodService := middleware2.NewGrpMethodsService()
	unimplementedAuthServiceServer := auth.UnimplementedAuthServiceServer{}
	db := provider.NewPostgresDB(conf)
	userRepository := repo.NewUserRepository(db)
	userService := user.NewUserService(userRepository)
	authHandler := &handler2.AuthHandler{
		UnimplementedAuthServiceServer: unimplementedAuthServiceServer,
		TokenMiddleware:                tokenMiddleware,
		UserService:                    userService,
	}
	unimplementedUserServiceServer := user2.UnimplementedUserServiceServer{}
	userHandler := &handler2.UserHandler{
		UnimplementedUserServiceServer: unimplementedUserServiceServer,
		UserService:                    userService,
		TokenMiddleware:                tokenMiddleware,
	}
	appProvider := &grpc.AppProvider{
		Conf:            conf,
		TokenMiddleware: tokenMiddleware,
		RoutesServices:  grpcMethodService,
		AuthHandler:     authHandler,
		UserHandler:     userHandler,
	}
	return appProvider
}
