server:
  http:
    port: 8000
  grpc:
    host: "127.0.0.1"
    grpc_port: 50051
    grpc_protocol: "tcp"

postgres:
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: gskeleton

redis:
  host: redis:6379

clickhouse:
  host: clickhouse
  port: 9000
  username: clickhouse
  password: clickhouse
  database: gskeleton

jwt:
  secret: "secret"
