server:
  http:
    port: 8000
  grpc:
    host: "127.0.0.1"
    grpc_port: 50051
    grpc_protocol: "tcp"

postgres:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database: gskeleton

jwt:
  secret: "secret"
