server:
  json_rpc:
    port: 8000
  grpc:
    host: "127.0.0.1"
    grpc_port: "50051"
    grpc_protocol: "tcp"

postgresql:
  host: xxx.xxx.xxx.xxx
  port: 5432
  user: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

jwt:
  secret: "secret"
